/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./src/components/cards/Card.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    CreateCustomer: typeof import('./src/components/modals/customers/CreateCustomer.vue')['default']
    CreateCustomerModal: typeof import('./src/components/modals/customers/CreateCustomerModal.vue')['default']
    CreateProductModal: typeof import('./src/components/modals/products/CreateProductModal.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteCustomer: typeof import('./src/components/modals/customers/DeleteCustomerModal.vue')['default']
    DeleteCustomerModal: typeof import('./src/components/modals/customers/DeleteCustomerModal.vue')['default']
    DeleteProductModal: typeof import('./src/components/modals/products/DeleteProductModal.vue')['default']
    DetailCustomerModal: typeof import('./src/components/modals/customers/DetailCustomerModal.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditCustomer: typeof import('./src/components/modals/customers/EditCustomer.vue')['default']
    EditCustomerModal: typeof import('./src/components/modals/customers/EditCustomerModal.vue')['default']
    EditProductModal: typeof import('./src/components/modals/products/EditProductModal.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    StatisticCard: typeof import('./src/components/cards/StatisticCard.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
